# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
      device = "/dev/disk/by-uuid/09a97e24-53cb-4ba7-b9fb-ef5cbd177932";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/624708e6-5e38-4e82-956b-3a3c2e961053";

  fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/B11B-F0BD";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" = {
      device = "/dev/disk/by-uuid/09a97e24-53cb-4ba7-b9fb-ef5cbd177932";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" = {
      device = "/dev/disk/by-uuid/09a97e24-53cb-4ba7-b9fb-ef5cbd177932";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/log" = {
      device = "/dev/disk/by-uuid/09a97e24-53cb-4ba7-b9fb-ef5cbd177932";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/swap" = {
      device = "/dev/disk/by-uuid/09a97e24-53cb-4ba7-b9fb-ef5cbd177932";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/.snapshots" = {
      device = "/dev/disk/by-uuid/09a97e24-53cb-4ba7-b9fb-ef5cbd177932";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" "compress=zstd" "noatime" ];
    };

  fileSystems."/var/lib/docker" = {
    device = "/dev/disk/by-uuid/09a97e24-53cb-4ba7-b9fb-ef5cbd177932";
    fsType = "btrfs";
    options = [ "subvol=@docker" "compress=zstd" "noatime" ];
  };

  swapDevices = [
    { device = "/swap/swapfile"; }
  ];
  zramSwap = {
    enable = true;
    memoryPercent = 10;
    priority = 100;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}